### ISSUE TITLE
Teeny coal not working

### ISSUE THREAD

**Issue by cursinorock** [Andrew6rant/Teeny-Coal#2]
Teeny coal are not working in any fornus :T

1.17.1
Fabric API: fabric-api-0.40.1+1.17
Fabric: 0.11.6
![imagem_2021-09-09_235821](https://user-images.githubusercontent.com/24946430/132792323-80417be5-bf84-4999-a94e-dd5c78425a12.png)

**Comment by Andrew6rant** [comment]
Hmm, I can't replicate this. Teeny Coal, Teeny Charcoal, and Teeny Sticks all work properly in furnaces. Can you send logs?

**Comment by cursinorock** [comment]
i can send you a video, but a log, how do i make a log? force crash?

**Comment by Andrew6rant** [comment]
It should be a text file in your .minecraft folder

**Comment by cursinorock** [comment]
soo, do i have to force a crash? the folder logs is empty

**Comment by cursinorock** [comment]
im sorry to bother, im a noob about this :T

**Comment by Andrew6rant** [comment]
Oh it is no problem, to be honest I don't really remember either. I always play with the console open, so I have access to my logs all the time.

According to the Fabric tutorial, it should be the `latest.log` file in your .minecraft\logs\ directory: https://fabricmc.net/wiki/player:tutorials:logs_ml:windows

you can also try and force a crash if you wish

**Comment by cursinorock** [comment]
[crash-2021-09-10_13.31.55-client.txt](https://github.com/Andrew6rant/Teeny-Coal/files/7145186/crash-2021-09-10_13.31.55-client.txt)
Here i do what i can xD

https://user-images.githubusercontent.com/24946430/132887372-1078fddc-445d-4a6a-8559-fd7848b9663a.mp4

**Comment by cursinorock** [comment]
[Adventure Craft BR-Beta03.zip](https://github.com/Andrew6rant/Teeny-Coal/files/7145215/Adventure.Craft.BR-Beta03.zip)
the modpack that i use, its a custom modpack. its not on curse but u can import there with this zip

**Comment by Andrew6rant** [comment]
Alright, I can replicate this. Super weird that it is happening, I need to do more testing to determine the cause of it, because somehow my mod's items are not being put on the fuel registry.

Here are some logs if you want to see them:

[latest.log](https://github.com/Andrew6rant/Teeny-Coal/files/7145345/latest.log)

[latest (1).log](https://github.com/Andrew6rant/Teeny-Coal/files/7145346/latest.1.log)

This modpack has quite a few error messages, and I think you might have accidentally put a forge mod in there as well (something is trying to register a recipe with "forge:crops" as the item tag).

**Comment by cursinorock** [comment]
thks, i will check, im not a expert, i just put some mds that i like together xD

**Comment by cursinorock** [comment]
no forge mods, i guess some mods works both forge and fabric and because of this, its trying to register some forge thing

**Comment by Andrew6rant** [comment]
Unfortunately, this issue seems to be completely out of my hands. I even attempted to register my fuels separate from the abstracted layer I made originally, and still no dice.

I am using the proper Fabric method to register fuels, and one or more of the mods in your list is messing with that

**Comment by cursinorock** [comment]
i found the mod confliting with yours, is the new Aether 
now, why? i have no idea xD
https://www.curseforge.com/minecraft/mc-mods/aether-reborn/files

**Comment by cursinorock** [comment]
one last thing, can you make 1 coal give 8 teeny ones, instead  of 9?

**Comment by Andrew6rant** [comment]
Alright, I have opened an issue on Aether's GitHub page. They are already aware of the issue (FuelRegistry not being added to) and have fixed it in dev builds. A fix should come out on their side soon.

Sometime in the future I will add configurable values for recipes and fuel values, but for now, I just made a new version of the mod for you, with all recipes respecting 8 instead of 9. Here it is: https://github.com/Andrew6rant/Teeny-Coal/releases/tag/1.0.2-1.17.x

I've marked it as a prerelease but it is a completely stable version.
